apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrailapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardrailapi
  template:
    metadata:
      labels:
        app: guardrailapi
    spec:
      containers:
        - name: guardrailapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: GUARDRAIL_ENV
              value: "{{ .Values.env.GUARDRAIL_ENV }}"
            - name: REDIS_URL
              value: "{{ .Values.env.REDIS_URL }}"
